services:
  _defaults:
    autowire: true

  Nyholm\Psr7\:
    resource: '%kernel.directory.root%/vendor/nyholm/psr7/src/*'

  #~ PSR
  Eureka\Component\Http\:
    resource: '%kernel.directory.root%/vendor/eureka/component-http/src/*'

  Psr\Log\:
    resource: '%kernel.directory.root%/vendor/psr/log/src/*'

  Psr\Cache\CacheItemPoolInterface:
    alias: Symfony\Component\Cache\Adapter\ArrayAdapter

  Symfony\Component\Cache\Adapter\ArrayAdapter: ~
