parameters:
  app.name: 'kernel'

services:
  # Main container
  Psr\Container\ContainerInterface:
    alias: 'service_container'

  # Main Logger
  logger:
    alias: Psr\Log\NullLogger

  # Main cache item pool
  cache:
    alias: Psr\Cache\CacheItemPoolInterface

  #~ PSR-17 Factories public alias (used by Application via container directly)
  response_factory:
    alias: Nyholm\Psr7\Factory\Psr17Factory
    public: true

  request_factory:
    alias: Nyholm\Psr7\Factory\Psr17Factory
    public: true

  server_request_factory:
    alias: Nyholm\Psr7\Factory\Psr17Factory
    public: true

  stream_factory:
    alias: Nyholm\Psr7\Factory\Psr17Factory
    public: true

  uri_factory:
    alias: Nyholm\Psr7\Factory\Psr17Factory
    public: true
