<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'test_json' => [[], ['rateLimiterQuota' => 100, 'rateLimiterTTL' => 60, '_controller' => 'Eureka\\Kernel\\Http\\Tests\\Mock\\TestController::testJsonAction'], [], [['text', '/test/json']], [], []],
    'test_json_limited' => [[], ['rateLimiterQuota' => 1, 'rateLimiterTTL' => 100, '_controller' => 'Eureka\\Kernel\\Http\\Tests\\Mock\\TestController::testJsonAction'], [], [['text', '/test/json/limited']], [], []],
    'test_html' => [[], ['someDefault' => 'value', '_controller' => 'Eureka\\Kernel\\Http\\Tests\\Mock\\TestController::testHtmlAction'], [], [['text', '/test/html']], [], []],
    'test_error_html_internal' => [[], ['_controller' => 'Eureka\\Kernel\\Http\\Tests\\Mock\\TestController::testInternalServerErrorHtmlAction'], [], [['text', '/test/error/html/internal-server-error']], [], []],
    'test_error_html_bad_request' => [[], ['_controller' => 'Eureka\\Kernel\\Http\\Tests\\Mock\\TestController::testBadRequestErrorHtmlAction'], [], [['text', '/test/error/html/bad-request']], [], []],
    'test_error_html_unauthorized' => [[], ['_controller' => 'Eureka\\Kernel\\Http\\Tests\\Mock\\TestController::testUnauthorizedErrorHtmlAction'], [], [['text', '/test/error/html/unauthorized']], [], []],
    'test_error_html_forbidden' => [[], ['_controller' => 'Eureka\\Kernel\\Http\\Tests\\Mock\\TestController::testForbiddenErrorHtmlAction'], [], [['text', '/test/error/html/forbidden']], [], []],
    'test_error_html_service_unavailable' => [[], ['_controller' => 'Eureka\\Kernel\\Http\\Tests\\Mock\\TestController::testServiceUnavailableErrorHtmlAction'], [], [['text', '/test/error/html/service-unavailable']], [], []],
    'test_error_html_conflict' => [[], ['_controller' => 'Eureka\\Kernel\\Http\\Tests\\Mock\\TestController::testConflictErrorHtmlAction'], [], [['text', '/test/error/html/conflict']], [], []],
    'test_error_action_not_exists' => [[], ['someDefault' => 'value', '_controller' => 'Eureka\\Kernel\\Http\\Tests\\Mock\\TestController::testErrorHtmlActionNotExists'], [], [['text', '/test/error/action-not-exists']], [], []],
];
